Controllers/AikaController.cs
using GoNorth.Config;
using GoNorth.Models.AikaViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace GoNorth.Controllers
{
    /// <summary>
    /// Aika controller
    /// </summary>
    [Authorize(Roles = RoleNames.Aika)]
    [ApiExplorerSettings(IgnoreApi = true)]
    public class AikaController : Controller
    {
        /// <summary>
        /// Misc config
        /// </summary>
        private readonly MiscConfig _config;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="configuration">Configuration</param>
        public AikaController(IOptions<ConfigurationData> configuration)
        {
            _config = configuration.Value.Misc;
        }

        /// <summary>
        /// Chapter Overview view
        /// </summary>
        /// <returns>View</returns>
        [HttpGet]
        public IActionResult Index()
        {
            SharedAikaViewModel viewModel = new SharedAikaViewModel();
            viewModel.DisableAutoSaving = _config.DisableAutoSaving.HasValue ? _config.DisableAutoSaving.Value : false;
            return View(viewModel);
        }

        /// <summary>
        /// Detail view
        /// </summary>
        /// <returns>View</returns>
        [HttpGet]
        public IActionResult Detail()
        {
            SharedAikaViewModel viewModel = new SharedAikaViewModel();
            viewModel.DisableAutoSaving = _config.DisableAutoSaving.HasValue ? _config.DisableAutoSaving.Value : false;
            return View(viewModel);
        }

        /// <summary>
        /// Quest view
        /// </summary>
        /// <returns>View</returns>
        [HttpGet]
        public IActionResult Quest()
        {
            QuestViewModel viewModel = new QuestViewModel();
            viewModel.DisableAutoSaving = _config.DisableAutoSaving.HasValue ? _config.DisableAutoSaving.Value : false;
            viewModel.AllowScriptSettingsForAllFieldTypes = _config.AllowScriptSettingsForAllFieldTypes.HasValue ? _config.AllowScriptSettingsForAllFieldTypes.Value : false;
            return View(viewModel);
        }

        /// <summary>
        /// Quest List view
        /// </summary>
        /// <returns>View</returns>
        [HttpGet]
        public IActionResult QuestList()
        {
            return View();
        }
    }
}

Controllers/EvneController.cs
using GoNorth.Config;
using GoNorth.Models.FlexFieldDatabaseModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace GoNorth.Controllers
{
    /// <summary>
    /// Evne controller
    /// </summary>
    [Authorize(Roles = RoleNames.Evne)]
    [ApiExplorerSettings(IgnoreApi = true)]
    public class EvneController : Controller
    {
        /// <summary>
        /// Misc config
        /// </summary>
        private readonly MiscConfig _config;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="configuration">Configuration</param>
        public EvneController(IOptions<ConfigurationData> configuration)
        {
            _config = configuration.Value.Misc;
        }

        /// <summary>
        /// Index view
        /// </summary>
        /// <returns>View</returns>
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Skill view
        /// </summary>
        /// <returns>View</returns>
        [HttpGet]
        public IActionResult Skill()
        {
            DetailFormViewModel viewModel = new DetailFormViewModel();
            viewModel.DisableAutoSaving = _config.DisableAutoSaving.HasValue ? _config.DisableAutoSaving.Value : false;
            viewModel.AllowScriptSettingsForAllFieldTypes = _config.AllowScriptSettingsForAllFieldTypes.HasValue ? _config.AllowScriptSettingsForAllFieldTypes.Value : false;
            return View(viewModel);
        }

        /// <summary>
        /// Manage Templates view
        /// </summary>
        /// <returns>View</returns>
        [Authorize(Roles = RoleNames.EvneTemplateManager)]
        [HttpGet]
        public IActionResult ManageTemplates()
        {
            return View();
        }
    }
}

Controllers/StyrController.cs
using GoNorth.Config;
using GoNorth.Models.FlexFieldDatabaseModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace GoNorth.Controllers
{
    /// <summary>
    /// Styr controller
    /// </summary>
    [Authorize(Roles = RoleNames.Styr)]
    [ApiExplorerSettings(IgnoreApi = true)]
    public class StyrController : Controller
    {
        /// <summary>
        /// Misc config
        /// </summary>
        private readonly MiscConfig _config;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="configuration">Configuration</param>
        public StyrController(IOptions<ConfigurationData> configuration)
        {
            _config = configuration.Value.Misc;
        }

        /// <summary>
        /// Index view
        /// </summary>
        /// <returns>View</returns>
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Item view
        /// </summary>
        /// <returns>View</returns>
        [HttpGet]
        public IActionResult Item()
        {
            DetailFormViewModel viewModel = new DetailFormViewModel();
            viewModel.DisableAutoSaving = _config.DisableAutoSaving.HasValue ? _config.DisableAutoSaving.Value : false;
            viewModel.AllowScriptSettingsForAllFieldTypes = _config.AllowScriptSettingsForAllFieldTypes.HasValue ? _config.AllowScriptSettingsForAllFieldTypes.Value : false;
            return View(viewModel);
        }

        /// <summary>
        /// Manage Templates view
        /// </summary>
        /// <returns>View</returns>
        [Authorize(Roles = RoleNames.StyrTemplateManager)]
        [HttpGet]
        public IActionResult ManageTemplates()
        {
            return View();
        }
    }
}

Controllers/TaskController.cs
using System;
using System.Linq;
using GoNorth.Data.TaskManagement;
using GoNorth.Models.TaskManagementViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GoNorth.Controllers
{
    /// <summary>
    /// Task controller
    /// </summary>
    [Authorize(Roles = RoleNames.Task)]
    [ApiExplorerSettings(IgnoreApi = true)]
    public class TaskController : Controller
    {
        /// <summary>
        /// Index view
        /// </summary>
        /// <returns>View</returns>
        [HttpGet]
        public IActionResult Index()
        {
            TaskBoardViewModel viewModel = new TaskBoardViewModel();
            viewModel.TaskStatus = Enum.GetValues(typeof(TaskStatus)).Cast<TaskStatus>().Select(s => new MappedTaskStatus {
                Value = (int)s,
                Name = s.ToString()
            }).ToList();
            return View(viewModel);
        }

        /// <summary>
        /// Manage Boards view
        /// </summary>
        /// <returns>View</returns>
        [Authorize(Roles = RoleNames.TaskBoardManager)]
        [HttpGet]
        public IActionResult ManageBoards()
        {
            return View();
        }
        
        /// <summary>
        /// Manage Task type view
        /// </summary>
        /// <returns>View</returns>
        [Authorize(Roles = RoleNames.TaskTypeManager)]
        [HttpGet]
        public IActionResult ManageTaskTypes()
        {
            return View();
        }
    }
}

Views/Shared/ChooseObjectDialog.cshtml
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer

<script type="text/javascript">
    window.GoNorth = window.GoNorth || {};
    window.GoNorth.ChooseObjectDialog = window.GoNorth.ChooseObjectDialog || {};
    window.GoNorth.ChooseObjectDialog.Localization = {
        TimeFormat: "@Localizer["TimeFormat"]",

        ObjectTypeNpc: "@Localizer["ObjectTypeNpc"]",
        ObjectTypeItem: "@Localizer["ObjectTypeItem"]",
        ObjectTypeSkill: "@Localizer["ObjectTypeSkill"]",
        ObjectTypeQuest: "@Localizer["ObjectTypeQuest"]",
        ObjectTypeWikiPage: "@Localizer["ObjectTypeWikiPage"]",
        ObjectTypeChapterDetail: "@Localizer["ObjectTypeChapterDetail"]",
        ObjectTypeDailyRoutine: "@Localizer["ObjectTypeDailyRoutine"]",
        ObjectTypeMarker: "@Localizer["ObjectTypeMarker"]"
    }
</script>

<div class="modal fade gn-chooseObjectDialog" role="dialog" data-bind="modal: showDialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title" data-bind="text: dialogTitle"></h4>
            </div>
            <div class="modal-body">
                <button type="button" class="btn btn-primary" data-bind="click: openCreatePage, visible: showNewButtonInDialog">
                    <i class="glyphicon glyphicon-plus"></i> @Localizer["CreateNewPage"]
                </button>

                <div class="alert alert-danger gn-defaultContentTopMargin" style="display: none" data-bind="visible: errorOccured">
                    <strong>@Localizer["Error"]</strong> @Localizer["ErrorOccured"]</span> 
                </div>

                <div class="form-group" data-bind="visible: showObjectTypeSelection" style="display: none">
                    <label for="gn-objectSelectionType">@Localizer["ObjectType"]</label>
                    <select class="form-control" id="gn-objectSelectionType" data-bind="options: availableObjectTypes, value: selectedObjectType, optionsText: 'objectLabel'">
                    </select>
                </div>

                <div class="input-group gn-commandWidgetTopMargin">
                    <input type="text" class="form-control" placeholder="@Localizer["Search"]" data-bind="value: dialogSearchPattern, enterPressed: startNewDialogSearch, enable: !dialogIsLoading()"/>
                    <span class="input-group-addon gn-clickable" data-bind="click: startNewDialogSearch, enable: !dialogIsLoading()" title="@Localizer["Search"]">
                        <i class="glyphicon glyphicon-search" data-bind="visible: !dialogIsLoading()"></i>
                        <i class="glyphicon glyphicon-refresh spinning" style="display: none" data-bind="visible: dialogIsLoading"></i>
                    </span>
                </div>

                <table class="table table-striped table-bordered gn-chooseObjectDialogTable">
                    <thead>
                    <tr>
                        <th>@Localizer["Name"]</th>
                        <th>@Localizer["Open"]</th>
                    </tr>
                    </thead>
                    <tbody data-bind="foreach: dialogEntries">
                        <tr>
                            <td>
                                <a class="gn-clickable" data-bind="click: function(obj) { $parent.handleObjectClick(obj); }">
                                    <i class="glyphicon glyphicon-triangle-right" data-bind="visible: expandCallback && !isLoadingExpandedObject() && !errorLoadingExpandedObject() && !isExpanded()"></i>
                                    <i class="glyphicon glyphicon-triangle-bottom" data-bind="visible: expandCallback && !isLoadingExpandedObject() && !errorLoadingExpandedObject() && isExpanded()" style="display: none"></i> 
                                    <i class="glyphicon glyphicon-refresh spinning" data-bind="visible: expandCallback && isLoadingExpandedObject() && !errorLoadingExpandedObject()" style="display: none"></i> 
                                    <i class="glyphicon glyphicon-warning-sign text-danger" data-bind="visible: expandCallback && !isLoadingExpandedObject() && errorLoadingExpandedObject()" style="display: none" title="@Localizer["ErrorOccured"]"></i>
                                    <span data-bind="text: name"></span>
                                </a>
                                <div data-bind="foreach: expandedObjects, visible: isExpanded" class="gn-chooseObjectDialogExpandedObjectsContainer">
                                    <div class="gn-chooseObjectDialogExpandedObjectsRow row">
                                        <div class="col-xs-4">
                                            <a class="gn-clickable" data-bind="text: name, click: function(obj) { $parents[1].handleObjectClick(obj); }"></a>
                                        </div>
                                        <div class="col-xs-8" data-bind="text: additionalName">
                                        </div>
                                    </div>
                                </div>
                            </td>
                            <td><a data-bind="attr: { href: openLink }" target="_blank">@Localizer["Open"]</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">   
                <div class="gn-dialogPagingContainer">
                    <button class="btn btn-default" data-bind="enable: dialogCurrentPage() > 0 && !dialogIsLoading(), click: prevDialogPage" title="@Localizer["PreviousPage"]">
                        <i class="glyphicon glyphicon-chevron-left" data-bind="visible: !dialogIsLoading()"></i>
                        <i class="glyphicon glyphicon-refresh spinning" style="display: none" data-bind="visible: dialogIsLoading"></i>
                    </button>
                    <button class="btn btn-default" data-bind="enable: dialogHasMore() && !dialogIsLoading(), click: nextDialogPage" title="@Localizer["NextPage"]">
                        <i class="glyphicon glyphicon-chevron-right" data-bind="visible: !dialogIsLoading()"></i>
                        <i class="glyphicon glyphicon-refresh spinning" style="display: none" data-bind="visible: dialogIsLoading"></i>
                    </button>
                </div>

                <button type="button" class="btn btn-default" data-bind="click: cancelDialog">@Localizer["Close"]</button>
            </div>
        </div>
    </div>
</div>

Views/Shared/ChooseScriptTypeDialog.cshtml
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer

<div class="modal fade" role="dialog" data-bind="modal: isVisible">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">@Localizer["ChooseScriptType"]</h4>
            </div>
            <div class="modal-body">
                <div>
                    <h5 class="gn-scriptTypeDialogHeader">@Localizer["NodeGraphScriptTitle"]</h5>
                    <p>@Localizer["NodeGraphScriptDescription"]</p>
                    <button type="button" class="btn btn-primary" data-bind="click: createNodeGraph">@Localizer["CreateNodeGraphScript"]</button>
                </div>
                <div class="gn-defaultContentTopMargin">
                    <h5 class="gn-scriptTypeDialogHeader">@Localizer["CodeScriptTitle"]</h5>
                    <p>@Localizer["CodeScriptDescription"]</p>
                    <button type="button" class="btn btn-primary" data-bind="click: createCodeScript">@Localizer["CreateCodeScript"]</button>
                </div>
            </div>
            <div class="modal-footer">   
                <button type="button" class="btn btn-default" data-bind="click: cancelDialog">@Localizer["Cancel"]</button>
            </div>
        </div>
    </div>
</div>

Views/Shared/CodeScriptEditor.cshtml
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer

<div class="modal fade" role="dialog" data-bind="modal: isVisible, modalBeforeClose: onClosingDialog">
    <div class="modal-dialog gn-codeScriptEditorDialog" data-bind="if: isVisible">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"><span data-bind="visible: !isEditing()">@Localizer["CreateCodeScript"]</span><span data-bind="visible: isEditing">@Localizer["EditCodeScript"]</span></h4>
            </div>
            <div class="modal-body">
                <form data-bind="attr: { id: 'gn-codeScriptEditorForm' + dialogId }">
                    <div class="form-group">
                        <label data-bind="attr: { for: 'gn-scriptCodeName' + dialogId }">@Localizer["Name"]</label>
                        <input type="text" class="form-control" placeholder="@Localizer["Name"]" name="scriptCodeName" data-bind="attr: { id: 'gn-scriptCodeName' + dialogId }, value: scriptName, enterPressed: saveCode" required/>
                    </div>
                    <div class="form-group" data-bind="if: codeEditorTheme() && codeEditorScriptLanguage()">
                        <label for="gn-scriptCode">@Localizer["Code"]</label>
                        <div id="gn-scriptCode" data-bind="codeEditor: scriptCode, codeEditorTheme: codeEditorTheme, codeEditorMode: codeEditorScriptLanguage" class="gn-exportManageTemplateCodeEditor"></div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">   
                <button type="button" class="btn btn-primary" data-bind="click: saveCode">@Localizer["Confirm"]</button>
                <button type="button" class="btn btn-default" data-bind="click: cancelDialog">@Localizer["Cancel"]</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" role="dialog" data-bind="modal: showConfirmCloseDialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">@Localizer["AreYouSure"]</h4>
            </div>
            <div class="modal-body">
                <p>@Localizer["ThereAreUnsavedChanges"]</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-bind="click: confirmCloseDialog">@Localizer["Yes"]</button>
                <button type="button" class="btn btn-default" data-bind="click: cancelCloseDialog">@Localizer["No"]</button>
            </div>
        </div>
    </div>
</div>

Views/Shared/NodeGraphDialogs.cshtml
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer

<!-- Delete Node Dialog -->
<div class="modal fade" role="dialog" data-bind="modal: showConfirmNodeDeleteDialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">@Localizer["AreYouSure"]</h4>
            </div>
            <div class="modal-body">
                <div class="alert alert-danger gn-defaultContentTopMargin" style="display: none" data-bind="visible: deleteErrorOccured">
                    <strong>@Localizer["Error"]</strong> @Localizer["ErrorOccured"]</span> <span data-bind="text: deleteErrorAdditionalInformation, visible: deleteErrorAdditionalInformation"></span>
                </div>
                
                <p>@Localizer["AreYouSureYouWantToDeleteTheNode"]</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-bind="click: deleteNode, disable: deleteLoading"><i class="glyphicon glyphicon-refresh spinning" style="display: none" data-bind="visible: deleteLoading"></i> <span data-bind="visible: !deleteLoading()">@Localizer["Yes"]</span></button>
                <button type="button" class="btn btn-default" data-bind="click: closeConfirmNodeDeleteDialog, disable: deleteLoading"><i class="glyphicon glyphicon-refresh spinning" style="display: none" data-bind="visible: deleteLoading"></i> <span data-bind="visible: !deleteLoading()">@Localizer["No"]</span></button>
            </div>
        </div>
    </div>
</div>

Views/Shared/NodeScriptEditorStyles.cshtml
<link rel="stylesheet" href="~/lib/jointjs/joint.css" />

<environment include="Development">
    <link rel="stylesheet" href="~/css/defaultNodes.css" />
</environment>
<environment exclude="Development">
    <link rel="stylesheet" href="~/css/defaultNodes.min.css" />
</environment>

Views/Shared/_Layout.cshtml
@using GoNorth.Data.User
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.AspNetCore.Http.Features

@inject IViewLocalizer Localizer
@inject GoNorth.Config.IConfigViewAccess AppSettings
@inject SignInManager<GoNorthUser> SignInManager

@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery Xsrf
@functions{
    public string GetAntiXsrfRequestToken()
    {
        return Xsrf.GetAndStoreTokens(Context).RequestToken;
    }
}

@{
    ITrackingConsentFeature consentFeature = Context.Features.Get<ITrackingConsentFeature>();
    bool showingGdprBanner = !consentFeature?.CanTrack ?? false;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GoNorth</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    @RenderSection("Styles", required: false)
</head>
<body>
    <input type="hidden" id="__RequestVerificationToken" value="@GetAntiXsrfRequestToken()">
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mainNavBar" id="gn-navbarCollapseExpand">
                    <span class="sr-only">@Localizer["ToogleNavigation"]</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand" title="@Localizer["Home"]">GoNorth</a>
            </div>
            <div class="navbar-collapse collapse" id="mainNavBar">
                @if (SignInManager.IsSignedIn(User))
                {
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Timeline" asp-action="Index">@Localizer["Timeline"]</a></li>
                    @if(User.IsInRole(RoleNames.Task))
                    {
                        <li><a asp-area="" asp-controller="Task" asp-action="Index">@Localizer["Tasks"]</a></li>
                    }
                    @if(User.IsInRole(RoleNames.Aika))
                    {
                        <li><a asp-area="" asp-controller="Aika" asp-action="Index">@Localizer["Aika"]</a></li>
                    }
                    @if(User.IsInRole(RoleNames.Kortisto))
                    {
                        <li><a asp-area="" asp-controller="Kortisto" asp-action="Index">@Localizer["Kortisto"]</a></li>
                    }
                    @if(User.IsInRole(RoleNames.Styr))
                    {
                        <li><a asp-area="" asp-controller="Styr" asp-action="Index">@Localizer["Styr"]</a></li>
                    }
                    @if(User.IsInRole(RoleNames.Evne))
                    {
                        <li><a asp-area="" asp-controller="Evne" asp-action="Index">@Localizer["Evne"]</a></li>
                    }
                    @if(User.IsInRole(RoleNames.Kirja))
                    {
                        <li><a asp-area="" asp-controller="Kirja" asp-action="Index">@Localizer["Kirja"]</a></li>
                    }
                    @if(User.IsInRole(RoleNames.Karta))
                    {
                        <li><a asp-area="" asp-controller="Karta" asp-action="Index">@Localizer["Karta"]</a></li>
                    }
                    @if(User.IsInRole(RoleNames.ImplementationStatusTracker))
                    {
                        <li><a asp-area="" asp-controller="ImplementationStatus" asp-action="Index">@Localizer["ImplementationStatus"]</a></li>
                    }
                    @if(User.IsInRole(RoleNames.ManageExportTemplates))
                    {
                        <li><a asp-area="" asp-controller="Export" asp-action="Index">@Localizer["ExportSettings"]</a></li>
                    }
                    @if(User.IsInRole(RoleNames.ProjectConfigManager))
                    {
                        <li><a asp-area="" asp-controller="ProjectConfig" asp-action="Index">@Localizer["ProjectConfig"]</a></li>
                    }
                </ul>
                }
                @await Html.PartialAsync("_LoginPartial")
            </div>
            @await Html.PartialAsync("_CookieConsentPartial")
        </div>
    </nav>

    <div class="container body-content gn-mainContainer @(showingGdprBanner ? "gn-mainContainerSmall" : "")">
        @RenderBody()
    </div>
    <hr />
    <footer>
        @if(AppSettings.IsUsingGdpr())
        {
            <small><a asp-area="" asp-controller="Privacy" asp-action="Index" class="text-muted">@Localizer["PrivacyPolicy"]</a></small>
        }

        @if(AppSettings.IsUsingGdpr() && AppSettings.IsUsingLegalNotice())
        {
            <span class="text-muted">|</span>
        }

        @if(AppSettings.IsUsingLegalNotice())
        {
            <small><a asp-area="" asp-controller="LegalNotice" asp-action="Index" class="text-muted">@Localizer["LegalNotice"]</a></small>
        }

        @if (SignInManager.IsSignedIn(User))
        {
            @if(AppSettings.IsUsingGdpr() || AppSettings.IsUsingLegalNotice())
            {
                <span class="text-muted">|</span>
            }

            <small class="text-muted">v<span>@GoNorthVersion.CurrentVersion.ToString()</span></small>
        }
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/knockout/dist/knockout.js"></script>
        <script src="~/lib/moment/moment.js"></script>
        <script src="~/js/Shared/shared.lib.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.6.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-vtXRMe3mGCbOeY7l30aIg8H9p3GdeSe4IFlP6G8JMa7o7lXvnz3GFKzPxzJdPfGK">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.4.1/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/knockout/3.5.1/knockout-latest.min.js"
                asp-fallback-src="~/lib/knockout/dist/knockout.js"
                asp-fallback-test="window.ko && ko.version"
                crossorigin="anonymous"
                integrity="sha384-PA7LgTHoYGwvEy2evWvC3sNOQlmK/vfk//sStiSk3QK3fUDO8oN3VKvHgSPyVKqx">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"
                asp-fallback-src="~/lib/moment/min/moment.min.js"
                asp-fallback-test="window.moment && moment.version"
                crossorigin="anonymous"
                integrity="sha384-Uz1UHyakAAz121kPY0Nx6ZGzYeUTy9zAtcpdwVmFCEwiTGPA2K6zSGgkKJEQfMhK">
        </script>
        <script src="~/js/Shared/shared.lib.min.js" asp-append-version="true"></script>
    </environment>

    <script type="text/javascript">
        moment.locale("@Localizer["MomentLocale"]");
    </script>

    @RenderSection("Scripts", required: false)

    @await Html.PartialAsync("~/Views/Shared/PromptService.cshtml")
</body>
</html>